In [1]:
import pandas as pd

In [2]:
#загружаем датасет
book=pd.read_csv('bookings.csv', sep=';')

In [3]:
book

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

In [4]:
book.shape

(119390, 21)

In [5]:
book.dtypes

Hotel                         object
Is Canceled                    int64
Lead Time                      int64
arrival full date             object
Arrival Date Year              int64
Arrival Date Month            object
Arrival Date Week Number       int64
Arrival Date Day of Month      int64
Stays in Weekend nights        int64
Stays in week nights           int64
stays total nights             int64
Adults                         int64
Children                     float64
Babies                         int64
Meal                          object
Country                       object
Reserved Room Type            object
Assigned room type            object
customer type                 object
Reservation Status            object
Reservation status_date       object
dtype: object

In [6]:
book.head(7)

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

In [7]:
book.columns

Index(['Hotel', 'Is Canceled', 'Lead Time', 'arrival full date',
       'Arrival Date Year', 'Arrival Date Month', 'Arrival Date Week Number',
       'Arrival Date Day of Month', 'Stays in Weekend nights',
       'Stays in week nights', 'stays total nights', 'Adults', 'Children',
       'Babies', 'Meal', 'Country', 'Reserved Room Type', 'Assigned room type',
       'customer type', 'Reservation Status', 'Reservation status_date'],
      dtype='object')

In [8]:
#Приведём названия колонок к нижнему регистру
book.columns=book.columns.str.lower()

In [9]:
#Заменим пробелы на знак нижнего подчеркивания
book.columns=book.columns.str.replace(' ','_')

In [10]:
book

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

In [11]:
#Посмотрим пользователи из каких стран совершили наибольшее число успешных бронирований
usp=book.query('is_canceled==0') \
    .groupby('country') \
    .aggregate({'is_canceled':'count'}) \
    .sort_values('is_canceled')

In [12]:
usp

         is_canceled
country
PLW                1
MDG                1
MLI                1
MMR                1
MRT                1
...              ...
DEU             6069
ESP             6391
FRA             8481
GBR             9676
PRT            21071

[165 rows x 1 columns]

In [13]:
#На сколько ночей в среднем бронируют отели разных типов
nig=book.query("hotel=='City Hotel'") \
    .aggregate({'stays_total_nights':'mean'})

In [14]:
nig

stays_total_nights    2.978142
dtype: float64

In [15]:
gin=book.query("hotel=='Resort Hotel'") \
    .aggregate({'stays_total_nights':'mean'})

In [16]:
gin

stays_total_nights    4.318547
dtype: float64

In [17]:
#Иногда тип номера, полученного клиентом, отличается от изначально забронированного. Проверим сколько таких случаев.
hi=book.query('assigned_room_type!=reserved_room_type') \
    .aggregate({'assigned_room_type':'count'})

In [18]:
hi

assigned_room_type    14917
dtype: int64

In [19]:
#На какой месяц чаще всего успешно оформляли бронь в 2016
lh=book.query('arrival_date_year==2016') \
    .groupby('arrival_date_month') \
    .aggregate({'is_canceled':'count'}) \
    .sort_values('is_canceled')

In [20]:
lh

                    is_canceled
arrival_date_month
January                    2248
December                   3860
February                   3891
November                   4454
July                       4572
March                      4824
August                     5063
June                       5292
September                  5394
April                      5428
May                        5478
October                    6203

In [21]:
#На какой месяц чаще всего успешно оформляли бронь в 2017
hl=book.query('arrival_date_year==2017') \
    .groupby('arrival_date_month') \
    .aggregate({'is_canceled':'count'}) \
    .sort_values('is_canceled')

In [22]:
hl

                    is_canceled
arrival_date_month
January                    3681
February                   4177
August                     4925
March                      4970
July                       5313
June                       5647
April                      5661
May                        6313

In [23]:
#Проверим, на какой месяц бронирования отеля типа City Hotel отменялись чаще всего в каждый из периодов
kl=book.query("hotel=='City Hotel' & is_canceled==1") \
    .groupby(['arrival_date_year', 'arrival_date_month']) \
    .aggregate({'is_canceled':'count'})

In [24]:
kl

                                      is_canceled
arrival_date_year arrival_date_month
2015              August                     1232
                  December                    668
                  July                        939
                  November                    301
                  October                    1321
                  September                  1543
2016              April                      1539
                  August                     1247
                  December                   1072
                  February                    930
                  January                     438
                  July                       1043
                  June                       1720
                  March                      1108
                  May                        1436
                  November                   1360
                  October                    1947
                  September                  1567
2017              April                      1926
                  August                     1123
                  February                    971
                  January                    1044
                  July                       1324
                  June                       1808
                  March                      1278
                  May                        2217

In [25]:
book.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,stays_total_nights,adults,children,babies
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,3.427900,1.856403,0.103890,0.007949
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,2.557439,0.579261,0.398561,0.097436
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,2.000000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,3.000000,2.000000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,4.000000,2.000000,0.000000,0.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,69.000000,55.000000,10.000000,10.000000

In [26]:
total_kids=book.children+book.babies

In [27]:
total_kids

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
119385    0.0
119386    0.0
119387    0.0
119388    0.0
119389    0.0
Length: 119390, dtype: float64

In [28]:
#Создадим колонку total_kids, объединив children и babies.
book=book.assign(total_kids=book.children+book.babies)

In [29]:
book

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date,total_kids
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02,0.0
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02,0.0
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06,0.0
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07,0.0
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07,0.0
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07,0.0
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07,0.0

In [30]:
#Посмотрим для отелей какого типа среднее значение переменной оказалось наибольшим
jk=book.query("hotel=='City Hotel'") \
    .aggregate({'total_kids':'mean'})

In [31]:
jk

total_kids    0.096311
dtype: float64

In [32]:
kj=book.query("hotel=='Resort Hotel'") \
    .aggregate({'total_kids':'mean'})

In [33]:
kj

total_kids    0.142586
dtype: float64

In [51]:
k=book.agg({'is_canceled':'count'})
g=book.query('total_kids>=1') \
    .agg({'is_canceled':'count'})
l=book.query('is_canceled==1 & total_kids>=1') \
    .agg({'is_canceled':'count'})
p=l/g
print(k)
print(g)
print(l)
print(p)

is_canceled    119390
dtype: int64
is_canceled    9332
dtype: int64
is_canceled    3259
dtype: int64
is_canceled    0.349228
dtype: float64

In [50]:
c=book.agg({'is_canceled':'count'})
u=book.query('total_kids<1') \
    .agg({'is_canceled':'count'})
b=book.query('is_canceled==1 & total_kids<1') \
    .agg({'is_canceled':'count'})
f=b/u
print(c)
print(u)
print(b)
print(f)

is_canceled    119390
dtype: int64
is_canceled    110054
dtype: int64
is_canceled    40961
dtype: int64
is_canceled    0.37219
dtype: float64